name: Release

on:
  push:
    branches:
      - main
      - feat/release
permissions:
  contents: write
jobs:
  version:
    name: Version and Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch all tags
        run: git fetch --tags

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm ci

      - name: Detect semver bump
        id: semver
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          if [[ "$BRANCH_NAME" =~ ^feat/|^feature/ ]]; then
            VERSION_PART="minor"
          elif [[ "$BRANCH_NAME" =~ ^major/|^breaking/ ]]; then
            VERSION_PART="major"
          else
            VERSION_PART="patch"
          fi
          echo "bump=$VERSION_PART" >> $GITHUB_OUTPUT

      - name: Bump version, update changelog and commit
        id: bump_version
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"          

          echo "Bumping version"
          npm version ${{ steps.semver.outputs.bump }} --no-git-tag-version

          echo "Syncing version across packages"
          npm run sync-version
          TAG_NAME=$(node -p "require('./package.json').version")
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT

          echo "Generating Changelog"
          COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          NEW_ENTRY="## ${TAG_NAME}
          - ${COMMIT_MESSAGE}

          "
          echo "$NEW_ENTRY$(cat CHANGELOG.md 2>/dev/null)" > CHANGELOG.md

          echo "Commiting changes"
          git add .
          git commit -m "chore(release): bump version to ${TAG_NAME} [skip ci]"
          git tag -a $TAG_NAME -m "chore(release): ${TAG_NAME}"
          git push --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  package:
    name: Build and Release
    needs: version
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Install dependencies (Ubuntu)
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt-get install -y libarchive-tools

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build and release (macOS)
        if: matrix.os == 'macos-latest'
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: true
          mac_certs: ${{ secrets.mac_certs }}
          mac_certs_password: ${{ secrets.mac_certs_password }}
        env:
          APPLE_ID: ${{ secrets.apple_id }}
          APPLE_ID_PASS: ${{ secrets.apple_id_pass }}
          APPLE_TEAM_ID: ${{ secrets.apple_team_id }}

      - name: Build and release (Windows/Linux)
        if: matrix.os != 'macos-latest'
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: true
